version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - backend
  app:
    container_name: yt-app
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env.dev
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
